require("settings")
require("mappings")
require("colorschemes-config.nightfox")
require("nvim-tree-config")
require("lsp-config.language-servers")
require("lsp-config.lsp-auto-com")
require("packer-config")
